#!/bin/sh

# arguments
[ "$1" = "--arguments" ] && { exit 0; }

# get broadcast addresses for each network
net=`( ifconfig | grep -o -E "Bcast:(.*?) " | cut -f2 -d":" ) 2>/dev/null`

# loop over networks running the scan
for n in $net;
do
  # first find SSH machines silently to prime the arp table
  nmap -T4 -n -p 22 --open --min-parallelism 100 "$n/24" | grep -e "scan report for" -e "ssh" > /dev/null
done

# then run arp to show machines pi MACs
arp -na | grep b8:27:eb | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
